### ISSUE TITLE
does nylas support send attachment using amazon s3 ?

### ISSUE THREAD

**Issue by TDtianzhenjiu** [nylas/nylas-java#9]
when i using java SDK send attachment, usually must  com.nylas.Files.upload method and using byte[] pass to it.
so  upload the file in backend，and it's cost double traffic .
i want upload file in frontend, after upload file successful notice  backend, and then java sdk to send email out,

does nylas support  send attachment  by using a s3  file link?

**Comment by ddlatham** [comment]
@TDtianzhenjiu, Nylas does not currently support directly retrieving file data from S3, so if you have data in S3 that you want to attach, you will need to transfer it from S3 to someplace that can access the Nylas API in order to upload it.  We will take the idea of direct S3 support into consideration for the future.
